## .cargo/config.toml
#[target.x86_64-pc-windows-msvc]
#rustflags = ["-C", "link-arg=/STACK:18388608"]
#
## .cargo/config.toml
#[target.x86_64-pc-windows-gnu]
#rustflags = ["-C", "link-arg=-Wl,--stack,18388608"]